import Link from 'next/link'
import { ErrorWrapper } from './error-wrapper'
export const metadata = {
  title: "Om's NextJs",
  description: 'Generated by Next.js',
  icons: {
    icon: '/logo.png',
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        style={{
          display: 'flex',
          flexDirection: 'column',
          width: '99%',
        }}
      >
        <header style={{ padding: '10px', backgroundColor: 'lavender' }}>
          <>
            <h1>Header</h1>
            <Link href="/">Home</Link>
          </>
        </header>
        <ErrorWrapper>{children}</ErrorWrapper>

        <footer style={{ padding: '10px', backgroundColor: 'lavender' }}>Footer</footer>
      </body>
    </html>
  )
}
